Force n_samples_data and n_samples_template to be integer variables i…
beridel/fast_matched_filter pull request #18
Opened 2018-05-11 17:45 UTC by ebeauce

I think there is a bit of misunderstanding on which bug I am talking about in the test function.

If n_samples_data and n_samples_template are not integer variables, which is currently the case if the user provides a sampling_rate that is not an integer (or just writing sampling_rate=100. instead of sampling_rate=100), then numpy cannot create the data matrix and the template matrix.

You can see this in the following screen shot:
![current_fmf](https://user-images.githubusercontent.com/31778001/39938479-16b8a0da-5521-11e8-8c54-aa9492f8e1bf.png)

My pull request is just a simple correction that makes sure that n_samples_data and n_samples_template are converted to integer variables before creating the arrays.

As you can see, the test function now works perfectly well even if the sampling rate is provided as a float variable.
![modified_fmf_float](https://user-images.githubusercontent.com/31778001/39938555-5454589e-5521-11e8-82ff-09c612d76797.png)

(Note the speedup in the second screen shot, explained by the implementation of the new cumulative sum ! ;) )

2018-05-11 17:52 UTC, beridel commented
Right, I agree with you. But in this case, the user will be testing data that does not correspond to what they entered.

My philosophy is that numpy should give an error and break the test function because the user put in bad choices. We shouldn't smooth it over for the user and give them finally something that is not what they asked for.

Maybe I'm too strict?

2018-05-11 17:53 UTC, ebeauce commented
Unrelated to this commit, I suspect there is an issue hidden in the implementation of the cumulative sum.

The csum vector is created with length (n_samples_data x n_stations x n_components) + 1. I understand that the additional sample is necessary to compute properly the sum of the square data for the first sliding window.

I would say this is necessary on each channel, so I would create a vector with length 
( (n_samples_data + 1) x n_stations x n_components)

In the current implementation, my understanding is that except for the first channel (s=0 and c =0), the sum of the square data in the first sliding window is wrong as it is computed as the difference between csum[n_samples_templates] and csum[-1], which is the cumulative sum from the last sample of the previous channel.

Am I missing something or is it really an issue to correct ?

2018-05-11 17:55 UTC, beridel commented
Yes, you are definitely correct that that is a problem.

I can get around to fixing that later today or this weekend; although if you want to fix it beforehand, I won't stop you!

2018-05-11 17:57 UTC, ebeauce commented
To answer your first response, I also agree with you that if converting the sampling_rate to integer really change its value, then we should raise an error.

I'm going to add a check like:
if float(int(sampling_rate)) != float(sampling_rate):
    print('Warning, bla bla bla')

I will see if I have time to fix this problem this afternoon, but I might not (I have several meetings ....).

2018-05-11 21:18 UTC, ebeauce commented
The cumulative sum should be properly computed now.

I also added a warning message in the test function in case the sampling rate is not a round number, and I made it more flexible so that round (but float) numbers are converted to integers.

2018-05-11 21:37 UTC, ebeauce commented
Yes dd was actually already declared ... but wasn't used ! So I used it instead of finding a new variable name.

2018-05-12 22:30 UTC, beridel requested changes

2018-05-12 22:30 UTC, beridel commented on fast_matched_filter/fast_matched_filter.py
I'm thinking we should check that the durations are a multiple of the sampling interval instead of checking for an integer sampling rate.

2018-05-13 15:19 UTC, ebeauce commented on fast_matched_filter/fast_matched_filter.py
Ok, now I'm checking the number of samples instead of the sampling rate.

2018-05-14 15:51 UTC, beridel approved these changes

2018-05-14 15:51 UTC, merged